# Netlify configuration file

[build]
  publish = "." # Serve files from the root directory

# Redirect all routes to index.html (for single-page apps or static sites)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
