# netlify.toml

[build]
  publish = "build"
  functions = "functions"
  command = "mkdir build && cp -r templates/. build/ && cp -r static/. build/static/"

# Configuration for your Python functions
[functions]
  included_files = ["best_model_out.keras"] # This must be directly under [functions]
# IMPORTANT: python_version should be a direct property of [functions]
python_version = "3.9" # <--- Ensure this is a direct key under [functions]

# Redirects
[[redirects]]
  from = "/api/predict-fabric"
  to = "/.netlify/functions/predict_fabric_pattern"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200