# netlify.toml

[build]
  publish = "build"
  functions = "functions"
  command = "mkdir build && cp -r templates/. build/ && cp -r static/. build/static/"

# Configuration for your Python functions
[functions]
  included_files = ["best_model_out.keras"]
  python_version = "3.9"                     # <--- Make sure this line is indented like this

# Redirects
[[redirects]]
  from = "/api/predict-fabric"
  to = "/.netlify/functions/predict_fabric_pattern"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200